remote_theme: mmistakes/minimal-mistakes
title: Sample Pages
description: Some Sample Pages
name: First Last

include: ["_pages","_posts"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
